version: '3'

services:
  pg:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: henrfarias
      POSTGRES_DB: branas
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data:
    external: true
